from typing import Protocol, Optional
from domain.entities import Regla, Sesion, Recomendacion, Retroalimentacion


class ReglaRepository(Protocol):
    def guardar(self, regla: Regla) -> None: ...
    def obtener(self, id: str) -> Optional[Regla]: ...
    def listar(self, area: Optional[str] = None) -> list[Regla]: ...
    def listar_activas(self, area: str) -> list[Regla]: ...


class SesionRepository(Protocol):
    def guardar(self, sesion: Sesion) -> None: ...
    def obtener(self, id: str) -> Optional[Sesion]: ...
    def actualizar_estado(self, id: str, estado: str) -> None: ...
    def contar(self) -> int: ...


class RecomendacionRepository(Protocol):
    def guardar(self, recomendacion: Recomendacion) -> None: ...
    def obtener(self, id: str) -> Optional[Recomendacion]: ...
    def listar(self) -> list[Recomendacion]: ...
    def contar(self) -> int: ...
    def contar_sin_recomendacion(self) -> int: ...
    def reglas_mas_activadas(self, limite: int = 5) -> list[dict]: ...


class FeedbackRepository(Protocol):
    def guardar(self, feedback: Retroalimentacion) -> None: ...
    def listar(self) -> list[Retroalimentacion]: ...
    def tasa_utilidad(self) -> float: ...
    def calificacion_promedio(self) -> float: ...
